package agents

// Policy represents the high-level trading strategy generated by agent LLMs, to be executed by their runtimes.
type Policy struct {
	Participation bool    `json:"participation"` // whether an agent chooses to participate in trading
	Bias          float64 `json:"bias"`          // [-1, 1]: bearish to bullish
	RiskAppetite  float64 `json:"risk_appetite"` // [0, 1]: order quantity scaling
	Aggression    float64 `json:"aggression"`    // [0, 1]: resting (<0.5) vs. crossing (>=0.5) tendency
	Rationale     string  `json:"rationale"`     // LLM-generated natural text justification
}
